{{- range $key, $con := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $key }}
  {{- if $con.labels }}
  labels:
    {{ toYaml $con.labels | nindent 4 }}
  {{- end }}
  namespace: {{ $.Values.global.namespace }}
spec:
  template:
    spec:
      containers:
      - name: container-{{ $key }}
        image: {{ $.Values.global.image }}
        command: ["/bin/sh", "-c"]
        args: ["cat /mnt/hello.txt"]
        volumeMounts:
        - name: container-{{ $key }}-volume
          mountPath: /mnt
      restartPolicy: Never
      volumes:
      - name: container-{{ $key }}-volume
      {{- if $con.secret }}
        secret:
          secretName: {{ $key }}-secret
      {{- else }}
        configMap:
          name: {{ $key }}-configmap
      {{- end }}
{{- end }}